import { build } from 'esbuild';
import { cp, mkdir, copyFile, readdir, readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
await mkdir('dist/public', { recursive: true });
await cp('public', 'dist/public', { recursive: true });
const { metafile } = await build({ entryPoints: ['client/app.ts'], bundle: true, outfile: 'dist/public/app.js', platform: 'browser', format: 'esm', target: 'chrome120', sourcemap: true, metafile: true });
await copyFile(require.resolve('@sentdm/voice/sw.js'), 'dist/public/sw.js');
await writeFile('THIRD_PARTY_NOTICES.md', await thirdPartyNotices(metafile));
console.log('Built portable server, dashboard, audio worker, Sent service worker, and third-party notices.');

// The committed bundle redistributes third-party code, so its licenses must ship with it.
async function thirdPartyNotices(metafile) {
  const dirs = new Map();
  for (const input of Object.keys(metafile.inputs)) {
    const match = input.match(/.*node_modules\/((?:@[^/]+\/)?[^/]+)\//);
    if (match) dirs.set(match[1], match[0]);
  }
  const packages = [];
  for (const [name, dir] of [...dirs].sort(([a], [b]) => a.localeCompare(b))) {
    const { version, license } = JSON.parse(await readFile(`${dir}package.json`, 'utf8'));
    const file = (await readdir(dir)).find((f) => /^licen[cs]e/i.test(f));
    const text = file ? (await readFile(dir + file, 'utf8')).replace(/\r\n/g, '\n').trim() : null;
    packages.push({ name, version, license, text });
  }
  return [
    '# Third-party notices',
    '',
    '`dist/public/app.js`, its source map, and `dist/public/sw.js` include the packages below. Each remains under its own license, not this repository\'s MIT license.',
    '',
    'Generated by `scripts/build.mjs`. Do not edit by hand.',
    '',
    '| Package | Version | License |',
    '| --- | --- | --- |',
    ...packages.map((p) => `| ${p.name} | ${p.version} | ${p.license.startsWith('SEE LICENSE') ? 'Custom, see below' : p.license} |`),
    ...packages.flatMap((p) => [
      '',
      `## ${p.name} ${p.version}`,
      '',
      ...(p.text
        ? ['```text', p.text, '```']
        : [`This package declares the ${p.license} license in its package.json but ships no license file or copyright notice.`]),
    ]),
    '',
  ].join('\n');
}
